spring:
  datasource:
    url: jdbc:mysql://localhost:10086/ssm_curd
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.alex.webadmin.*
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      filter:
        stat:
          slow-sql-log-level: 1000   
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false



  jdbc:
    template: 
      query-timeout: 3
  